# Generated by Django 5.1.1 on 2025-01-01 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Description', models.TextField()),
                ('Sunlight', models.CharField(max_length=50)),
                ('Soil_type', models.CharField(max_length=50)),
                ('Water_requirements', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=254)),
                ('Join_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlantingCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Season', models.CharField(max_length=50)),
                ('Optimal_start_date', models.DateField()),
                ('Optimal_end_date', models.DateField()),
                ('Plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_entries', to='app.plant')),
            ],
        ),
        migrations.CreateModel(
            name='PlantingTip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tip', models.TextField()),
                ('Step_number', models.TextField()),
                ('Plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tips', to='app.plant')),
            ],
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Reminder_date', models.DateField()),
                ('Calendar_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='app.plantingcalendar')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='app.user')),
            ],
        ),
    ]
